// This file was auto-generated by ML.NET Model Builder. 

using MLPOPITKA;


Console.WriteLine("Вязкость конечного шлака при температуре 1500 °С");
Console.WriteLine("Фактическое значение вязкости");
Console.WriteLine("31.12.2022 0:00: 2,602433");
Console.WriteLine("31.12.2022 8:00: 2,834622");
Console.WriteLine("31.12.2022 16:00: 3,114118");

string[] dateArr = { "31.12.2022 0:00", "31.12.2022 8:00", "31.12.2022 16:00" };

foreach (string i in dateArr)

{ 

    MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
    {
        Date = i
    };

    // Make a single prediction on the sample data and print results
    var predictionResult = MLModel1.Predict(sampleData);

    Console.WriteLine($"Прогнозируемая Вязкость конечного шлака при температуре 1500 °С {i}: {predictionResult.Score}");
}
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();
